// <auto-generated />
using GamesHub.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesHub.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325110236_AddBoardJsonAndNewGames")]
    partial class AddBoardJsonAndNewGames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("GamesHub.Server.Data.Entities.GameEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = "minzzle-fives",
                            Description = "Cover every edge of the graph using moves of exactly 5 edges.",
                            Name = "Minzzle Fives"
                        },
                        new
                        {
                            Id = "minzzle-swipes",
                            Description = "Slide rows and columns to restore the color grid.",
                            Name = "Minzzle Swipes"
                        },
                        new
                        {
                            Id = "minzzle-swipes-hex",
                            Description = "Slide hexagonal lines to restore the color pattern.",
                            Name = "Minzzle Swipes Hex"
                        });
                });

            modelBuilder.Entity("GamesHub.Server.Data.Entities.LevelEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Board");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EdgesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Edges");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MoveLen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nodes");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SolutionJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("Solution");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = "level-001",
                            Difficulty = 1,
                            EdgesJson = "[{\"id\":0,\"a\":0,\"b\":1},{\"id\":1,\"a\":1,\"b\":2},{\"id\":2,\"a\":2,\"b\":3},{\"id\":3,\"a\":4,\"b\":5},{\"id\":4,\"a\":5,\"b\":6},{\"id\":5,\"a\":6,\"b\":7},{\"id\":6,\"a\":0,\"b\":4},{\"id\":7,\"a\":1,\"b\":5},{\"id\":8,\"a\":2,\"b\":6},{\"id\":9,\"a\":3,\"b\":7}]",
                            GameId = "minzzle-fives",
                            MoveLen = 5,
                            Name = "First Steps",
                            NodesJson = "[{\"id\":0,\"x\":0,\"y\":0},{\"id\":1,\"x\":1,\"y\":0},{\"id\":2,\"x\":2,\"y\":0},{\"id\":3,\"x\":3,\"y\":0},{\"id\":4,\"x\":0,\"y\":1},{\"id\":5,\"x\":1,\"y\":1},{\"id\":6,\"x\":2,\"y\":1},{\"id\":7,\"x\":3,\"y\":1}]",
                            SchemaVersion = 1
                        },
                        new
                        {
                            Id = "level-002",
                            Difficulty = 2,
                            EdgesJson = "[{\"id\":0,\"a\":0,\"b\":1},{\"id\":1,\"a\":1,\"b\":2},{\"id\":2,\"a\":3,\"b\":4},{\"id\":3,\"a\":4,\"b\":5},{\"id\":4,\"a\":6,\"b\":7},{\"id\":5,\"a\":7,\"b\":8},{\"id\":6,\"a\":0,\"b\":3},{\"id\":7,\"a\":1,\"b\":4},{\"id\":8,\"a\":2,\"b\":5},{\"id\":9,\"a\":3,\"b\":6},{\"id\":10,\"a\":4,\"b\":7},{\"id\":11,\"a\":5,\"b\":8},{\"id\":12,\"a\":0,\"b\":4},{\"id\":13,\"a\":1,\"b\":5},{\"id\":14,\"a\":3,\"b\":7},{\"id\":15,\"a\":4,\"b\":8},{\"id\":16,\"a\":1,\"b\":3},{\"id\":17,\"a\":2,\"b\":4},{\"id\":18,\"a\":4,\"b\":6},{\"id\":19,\"a\":5,\"b\":7}]",
                            GameId = "minzzle-fives",
                            MoveLen = 5,
                            Name = "Crossroads",
                            NodesJson = "[{\"id\":0,\"x\":0,\"y\":0},{\"id\":1,\"x\":1,\"y\":0},{\"id\":2,\"x\":2,\"y\":0},{\"id\":3,\"x\":0,\"y\":1},{\"id\":4,\"x\":1,\"y\":1},{\"id\":5,\"x\":2,\"y\":1},{\"id\":6,\"x\":0,\"y\":2},{\"id\":7,\"x\":1,\"y\":2},{\"id\":8,\"x\":2,\"y\":2}]",
                            SchemaVersion = 1
                        },
                        new
                        {
                            Id = "level-003",
                            Difficulty = 3,
                            EdgesJson = "[{\"id\":0,\"a\":0,\"b\":1},{\"id\":1,\"a\":1,\"b\":2},{\"id\":2,\"a\":2,\"b\":3},{\"id\":3,\"a\":3,\"b\":4},{\"id\":4,\"a\":5,\"b\":6},{\"id\":5,\"a\":6,\"b\":7},{\"id\":6,\"a\":7,\"b\":8},{\"id\":7,\"a\":8,\"b\":9},{\"id\":8,\"a\":10,\"b\":11},{\"id\":9,\"a\":11,\"b\":12},{\"id\":10,\"a\":12,\"b\":13},{\"id\":11,\"a\":13,\"b\":14},{\"id\":12,\"a\":0,\"b\":5},{\"id\":13,\"a\":1,\"b\":6},{\"id\":14,\"a\":2,\"b\":7},{\"id\":15,\"a\":3,\"b\":8},{\"id\":16,\"a\":4,\"b\":9},{\"id\":17,\"a\":5,\"b\":10},{\"id\":18,\"a\":6,\"b\":11},{\"id\":19,\"a\":7,\"b\":12},{\"id\":20,\"a\":8,\"b\":13},{\"id\":21,\"a\":9,\"b\":14},{\"id\":22,\"a\":0,\"b\":6},{\"id\":23,\"a\":2,\"b\":8},{\"id\":24,\"a\":7,\"b\":11}]",
                            GameId = "minzzle-fives",
                            MoveLen = 5,
                            Name = "Wide Grid",
                            NodesJson = "[{\"id\":0,\"x\":0,\"y\":0},{\"id\":1,\"x\":1,\"y\":0},{\"id\":2,\"x\":2,\"y\":0},{\"id\":3,\"x\":3,\"y\":0},{\"id\":4,\"x\":4,\"y\":0},{\"id\":5,\"x\":0,\"y\":1},{\"id\":6,\"x\":1,\"y\":1},{\"id\":7,\"x\":2,\"y\":1},{\"id\":8,\"x\":3,\"y\":1},{\"id\":9,\"x\":4,\"y\":1},{\"id\":10,\"x\":0,\"y\":2},{\"id\":11,\"x\":1,\"y\":2},{\"id\":12,\"x\":2,\"y\":2},{\"id\":13,\"x\":3,\"y\":2},{\"id\":14,\"x\":4,\"y\":2}]",
                            SchemaVersion = 1
                        },
                        new
                        {
                            Id = "swipes-001",
                            BoardJson = "{\"rows\":4,\"cols\":4,\"solved\":[[\"#3b82f6\",\"#3b82f6\",\"#eab308\",\"#eab308\"],[\"#3b82f6\",\"#3b82f6\",\"#eab308\",\"#eab308\"],[\"#ef4444\",\"#ef4444\",\"#22c55e\",\"#22c55e\"],[\"#ef4444\",\"#ef4444\",\"#22c55e\",\"#22c55e\"]],\"scrambleMoves\":[{\"type\":\"row\",\"index\":1},{\"type\":\"col\",\"index\":2}]}",
                            Difficulty = 1,
                            EdgesJson = "[]",
                            GameId = "minzzle-swipes",
                            MoveLen = 2,
                            Name = "Tiny Quadrants",
                            NodesJson = "[]",
                            SchemaVersion = 1
                        },
                        new
                        {
                            Id = "swipes-002",
                            BoardJson = "{\"rows\":6,\"cols\":6,\"solved\":[[\"#3b82f6\",\"#3b82f6\",\"#3b82f6\",\"#eab308\",\"#eab308\",\"#eab308\"],[\"#3b82f6\",\"#3b82f6\",\"#3b82f6\",\"#eab308\",\"#eab308\",\"#eab308\"],[\"#3b82f6\",\"#3b82f6\",\"#3b82f6\",\"#eab308\",\"#eab308\",\"#eab308\"],[\"#ef4444\",\"#ef4444\",\"#ef4444\",\"#22c55e\",\"#22c55e\",\"#22c55e\"],[\"#ef4444\",\"#ef4444\",\"#ef4444\",\"#22c55e\",\"#22c55e\",\"#22c55e\"],[\"#ef4444\",\"#ef4444\",\"#ef4444\",\"#22c55e\",\"#22c55e\",\"#22c55e\"]],\"scrambleMoves\":[{\"type\":\"row\",\"index\":1},{\"type\":\"col\",\"index\":4},{\"type\":\"row\",\"index\":3},{\"type\":\"col\",\"index\":0},{\"type\":\"row\",\"index\":5}]}",
                            Difficulty = 2,
                            EdgesJson = "[]",
                            GameId = "minzzle-swipes",
                            MoveLen = 5,
                            Name = "Classic Quadrants",
                            NodesJson = "[]",
                            SchemaVersion = 1
                        },
                        new
                        {
                            Id = "swipes-003",
                            BoardJson = "{\"rows\":6,\"cols\":6,\"solved\":[[\"#3b82f6\",\"#3b82f6\",\"#3b82f6\",\"#eab308\",\"#eab308\",\"#eab308\"],[\"#3b82f6\",\"#3b82f6\",\"#3b82f6\",\"#eab308\",\"#eab308\",\"#eab308\"],[\"#3b82f6\",\"#3b82f6\",\"#3b82f6\",\"#eab308\",\"#eab308\",\"#eab308\"],[\"#ef4444\",\"#ef4444\",\"#ef4444\",\"#22c55e\",\"#22c55e\",\"#22c55e\"],[\"#ef4444\",\"#ef4444\",\"#ef4444\",\"#22c55e\",\"#22c55e\",\"#22c55e\"],[\"#ef4444\",\"#ef4444\",\"#ef4444\",\"#22c55e\",\"#22c55e\",\"#22c55e\"]],\"scrambleMoves\":[{\"type\":\"row\",\"index\":0},{\"type\":\"col\",\"index\":2},{\"type\":\"row\",\"index\":4},{\"type\":\"col\",\"index\":5},{\"type\":\"row\",\"index\":2},{\"type\":\"col\",\"index\":1},{\"type\":\"row\",\"index\":3},{\"type\":\"col\",\"index\":3}]}",
                            Difficulty = 3,
                            EdgesJson = "[]",
                            GameId = "minzzle-swipes",
                            MoveLen = 8,
                            Name = "Tangled Quadrants",
                            NodesJson = "[]",
                            SchemaVersion = 1
                        },
                        new
                        {
                            Id = "hex-001",
                            BoardJson = "{\"side\":2,\"colors\":[\"#3b82f6\",\"#eab308\",\"#22c55e\",\"#ef4444\",\"#a855f7\",\"#f97316\"],\"scrambleMoves\":[{\"axis\":\"horizontal\",\"lineIndex\":1},{\"axis\":\"diagL\",\"lineIndex\":2},{\"axis\":\"diagR\",\"lineIndex\":0}]}",
                            Difficulty = 1,
                            EdgesJson = "[]",
                            GameId = "minzzle-swipes-hex",
                            MoveLen = 3,
                            Name = "Hex Intro",
                            NodesJson = "[]",
                            SchemaVersion = 1
                        },
                        new
                        {
                            Id = "hex-002",
                            BoardJson = "{\"side\":3,\"colors\":[\"#3b82f6\",\"#eab308\",\"#22c55e\",\"#ef4444\",\"#a855f7\",\"#f97316\"],\"scrambleMoves\":[{\"axis\":\"horizontal\",\"lineIndex\":2},{\"axis\":\"diagR\",\"lineIndex\":3},{\"axis\":\"diagL\",\"lineIndex\":1},{\"axis\":\"horizontal\",\"lineIndex\":4},{\"axis\":\"diagR\",\"lineIndex\":1}]}",
                            Difficulty = 2,
                            EdgesJson = "[]",
                            GameId = "minzzle-swipes-hex",
                            MoveLen = 5,
                            Name = "Hex Medium",
                            NodesJson = "[]",
                            SchemaVersion = 1
                        },
                        new
                        {
                            Id = "hex-003",
                            BoardJson = "{\"side\":3,\"colors\":[\"#3b82f6\",\"#eab308\",\"#22c55e\",\"#ef4444\",\"#a855f7\",\"#f97316\"],\"scrambleMoves\":[{\"axis\":\"horizontal\",\"lineIndex\":0},{\"axis\":\"diagL\",\"lineIndex\":3},{\"axis\":\"diagR\",\"lineIndex\":2},{\"axis\":\"horizontal\",\"lineIndex\":3},{\"axis\":\"diagL\",\"lineIndex\":0},{\"axis\":\"diagR\",\"lineIndex\":4},{\"axis\":\"horizontal\",\"lineIndex\":1},{\"axis\":\"diagL\",\"lineIndex\":2}]}",
                            Difficulty = 3,
                            EdgesJson = "[]",
                            GameId = "minzzle-swipes-hex",
                            MoveLen = 8,
                            Name = "Hex Challenge",
                            NodesJson = "[]",
                            SchemaVersion = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
